spring:
  profiles: cloud
  application:
   name: attendees
  cloud:
    services:
      registrationMethod: route
security:
  user: admin
    password: admin
jpa:
  hibernate:
  ddl-auto: update
datasource:
  initialize: false


