spring:
  profiles: cloud
  application:
   name: attendees
  cloud:
    services:
      registrationMethod: route
spring.jpa.hibernate.ddl-auto: update
spring.datasource.initialize: false
security:
  basic:
    enabled: false
 management:
   security:
     enabled: false
