spring:
 profiles: cloud
eureka:
  enableSelfPreservation: true
  registration:
    enabled: true
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${vcap.application.uris[0]}/eureka/
