spring:
 profiles: cloud
eureka:
  enableSelfPreservation: true
  registration:
    enabled: true
  instance:
    hostname: ${vcap.application.uris[0]}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    nonSecurePort: 80
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${vcap.application.uris[0]}/eureka/
