spring:
 profiles: cloud
eureka:
  instance:
    hostname: localhost
    nonSecurePort: 80
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server.bosh-lite.com/eureka
