spring:
 profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.application_uris[0]}
    nonSecurePort: 80
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
