spring:
 profiles: cloud
eureka:
  instance:
    hostname: localhost
    nonSecurePort: 80
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server.bosh-lite.com/eureka/
log4j:
  rootCategory: INFO,stdout
  appender:
    stdout: org.apache.log4j.ConsoleAppender
      layout: com.netflix.logging.log4jAdapter.NFPatternLayout
  logger:
    conversionPattern: %d %-5p %C:%L [%t] [%M] %m%nasyncAppenders=INFO,stdout
