message: "Olá Mundo!"
spring:
  profiles: cloud
  application:
   name: hello-service
ribbon:
  eureka:
   enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://${vcap.services.eureka-service.credentials.uri}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
