spring:
  application:
     name: portfolio-service
  jpa:
     hibernate:
        ddl-auto: update
security:
  basic:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
