spring:
  application:
     name: web-service
eureka:
  client:
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 3
    symbols:
      it: EMC,ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
